apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - namespace.yaml
  - operator-group.yaml

patches:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: crunchy-postgres-operator
    path: patch-subscription.yaml
