apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: odf-console
spec:
  displayName: ODF Plugin
  backend:
    service:
      basePath: /
      name: odf-console-service
      namespace: openshift-storage
      port: 9001
    type: Service
