apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../clustered-ephemeral

components:
  - ../../components/acceptors/one-way-tls
  - ../../components/certificates/cert-manager/console-ssl-keystore
  - ../../components/certificates/cert-manager/acceptor-ssl-keystore
  - ../../components/certificates/public-ca-truststores/letsencrypt-prod
  - ../../components/certificates/public-ca-truststores/letsencrypt-prod/console-ssl-keystore
  - ../../components/certificates/public-ca-truststores/letsencrypt-prod/acceptor-ssl-truststore

patches:
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
    patch: |-
      - op: replace
        path: /spec/issuerRef
        value:
          group: cert-manager.io
          kind: ClusterIssuer
          name: letsencrypt-prod
