apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - ../_base

patches:
  - target:
      group: ''
      version: v1
      kind: Secret
      name: broker-jdbc-configs-bp
    patch: |-
      - op: replace
        path: /stringData/jdbc-lock-timing.broker.properties
        value: |
          storeConfiguration.jdbcLockAcquisitionTimeoutMillis=-1
          storeConfiguration.jdbcLockExpirationMillis=4000
          storeConfiguration.jdbcLockRenewPeriodMillis=2000
