apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      group: broker.amq.io
      version: v1beta1
      kind: ActiveMQArtemis
      name: default
    patch: |-
      - op: test
        path: /spec/addressSettings/addressSetting/0/match
        value: '#'

      - op: replace
        path: /spec/addressSettings/addressSetting/0/enableMetrics
        value: true

      - op: replace
        path: /spec/addressSettings/addressSetting/0/messageCounterHistoryDayLimit
        value: 7
