apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: default
  labels:
    team: prometheus
spec:
  selector:
    matchLabels:
      application: default-app
  endpoints:
    - port: wconsj
