apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - acceptor-ssl-truststore.yaml

components:
  - ../acceptor-ssl-keystore

replacements:
  - source:
      group: ''
      version: v1
      kind: Secret
      name: acceptor-ssl-keystore
      fieldPath: stringData.keyStorePassword
    targets:
      - select:
          group: ''
          version: v1
          kind: Secret
          name: acceptor-ssl-truststore
        fieldPaths:
          - stringData.trustStorePassword
