apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      group: broker.amq.io
      version: v1beta1
      kind: ActiveMQArtemis
      name: default
    patch: |-
      - op: replace
        path: /spec/deploymentPlan/persistenceEnabled
        value: false

      - op: test
        path: /spec/brokerProperties/1
        value: |-
          persistenceEnabled=false
