apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      group: broker.amq.io
      version: v1beta1
      kind: ActiveMQArtemis
      name: default
    patch: |-
      # Default size to 3 instead of 1 for clustered deployments; assume that overlay will change if needed
      - op: replace
        path: /spec/deploymentPlan/size
        value: 3

      # Turn clustering on from the AMQ Broker operator; leave everything else as-is so operator can set up the cluster
      - op: replace
        path: /spec/deploymentPlan/clustered
        value: true

      # Enable message migration for clustered deployment
      - op: replace
        path: /spec/deploymentPlan/messageMigration
        value: true
