apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # This key doesn't exist, cert-manager creates it
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    preferredChain: ''
    solvers:
      - http01:
          ingress:
            class: openshift-default
