apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - broker-logging-config.yaml

patches:
  - target:
      group: broker.amq.io
      version: v1beta1
      kind: ActiveMQArtemis
      name: default
    patch: |-
      - op: add
        path: /spec/deploymentPlan/extraMounts/secrets/-
        value: broker-logging-config
