---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-file-integrity

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable'
    target:
      kind: Subscription
      name: file-integrity-operator
