apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base

components:
  - ../../../components/clustering/none
  - ../../../components/persistence/jdbc/postgresql
  - ../../../components/high-availability/ha-leader-follower/leader
