apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: onepassword-connect-anyuid
subjects:
  - kind: ServiceAccount
    name: onepassword-connect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
