apiVersion: v1
kind: Secret
metadata:
  name: cluster-ssl-keystore
type: Opaque
stringData:
  keyStorePath: '/amq/extra/secrets/cluster-ssl-certificate/keystore.jks'
  keyStorePassword: 'super-secret-cluster-keystore-password'
