apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      group: broker.amq.io
      version: v1beta1
      kind: ActiveMQArtemis
      name: default
    patch: |-
      # Ask operator to create PVCs for pod persistence
      - op: replace
        path: /spec/deploymentPlan/persistenceEnabled
        value: true

      # Tell broker to enable persistence
      - op: test
        path: /spec/brokerProperties/1
        value: |-
          persistenceEnabled=false
      - op: replace
        path: /spec/brokerProperties/1
        value: |-
          persistenceEnabled=true

      # Set storage size (which can be overridden in overlay)
      - op: add
        path: /spec/deploymentPlan/storage
        value:
          size: 4Gi
          # storageClassName: gp3

      # Set default catch-all address setting to PAGE instead of BLOCK
      - op: test
        path: /spec/addressSettings/addressSetting/0/match
        value: '#'
      - op: replace
        path: /spec/addressSettings/addressSetting/0/addressFullPolicy
        value: PAGE
