apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: self-signed-ca-root
  namespace: cert-manager
spec:
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: self-signed-root
  isCA: true
  commonName: self-signed-ca-root
  secretName: self-signed-ca-root
  privateKey:
    algorithm: ECDSA
    size: 256
