apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - default-pguser-dbuser.yaml

patches:
  - target:
      group: postgres-operator.crunchydata.com
      version: v1beta1
      kind: PostgresCluster
      name: default
    path: patch-add-user-and-database.yaml
