apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      group: registry.apicur.io
      version: v1
      kind: ApicurioRegistry
      name: default
    path: patch-apicurio-registry.yaml
