apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - cluster-ssl-truststore.yaml

replacements:
  - source:
      group: ''
      version: v1
      kind: ConfigMap
      name: letsencrypt-prod-truststore
      fieldPath: data.trustStorePassword
    targets:
      - select:
          group: ''
          version: v1
          kind: Secret
          name: cluster-ssl-truststore
        fieldPaths:
          - stringData.trustStorePassword
  - source:
      group: ''
      version: v1
      kind: ConfigMap
      name: letsencrypt-prod-truststore
      fieldPath: data.trustStorePath
    targets:
      - select:
          group: ''
          version: v1
          kind: Secret
          name: cluster-ssl-truststore
        fieldPaths:
          - stringData.trustStorePath
