apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - acceptor-ssl-keystore.yaml
  - acceptor-ssl-certificate.yaml

patches:
  - target:
      group: broker.amq.io
      version: v1beta1
      kind: ActiveMQArtemis
      name: default
    patch: |-
      - op: add
        path: /spec/deploymentPlan/extraMounts/secrets/-
        value: acceptor-ssl-certificate
