apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - broker-addresses-bp.yaml
  - broker-address-settings-bp.yaml
  - broker-address-security-bp.yaml

patches:
  - target:
      group: broker.amq.io
      version: v1beta1
      kind: ActiveMQArtemis
      name: default
    patch: |-
      # Add broperProperties secrets
      - op: add
        path: /spec/deploymentPlan/extraMounts/secrets/-
        value: broker-addresses-bp
      - op: add
        path: /spec/deploymentPlan/extraMounts/secrets/-
        value: broker-address-settings-bp
      - op: add
        path: /spec/deploymentPlan/extraMounts/secrets/-
        value: broker-address-security-bp

      # Add example address settings (this may be removed in an overlay if unneeded)
      - op: add
        path: /spec/addressSettings/addressSetting/-
        value:
          match: 'EXAMPLE.SETTINGS.#'

          autoCreateAddresses: true
          autoCreateQueues: true
          autoCreateDeadLetterResources: true
