apiVersion: apps/v1
kind: Deployment
metadata:
  name: onepassword-connect-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onepassword-connect-operator
  template:
    metadata:
      labels:
        app: onepassword-connect-operator
    spec:
      serviceAccountName: onepassword-connect-operator
      containers:
        - name: onepassword-connect-operator
          image: 1password/onepassword-operator:1.8.0
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 65532
            runAsGroup: 65532
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          command: ["/manager"]
          args: [--zap-log-level=info]
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: onepassword-connect-operator
            - name: OP_CONNECT_HOST
              value: http://onepassword-connect:8080
            - name: POLLING_INTERVAL
              value: "600"
            - name: OP_CONNECT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: onepassword-token
                  key: token
            - name: AUTO_RESTART
              value: "false"
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
