apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: onepassword

commonLabels:
  app.kubernetes.io/name: onepassword-connect-operator
  app.kubernetes.io/component: operator

resources:
  - serviceaccount.yaml
  - scc.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml

secretGenerator:
  - name: onepassword-token
    literals:
      - token=Y2hhbmdlbWU=

generatorOptions:
  disableNameSuffixHash: true
