apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: onepassword-connect-operator-anyuid
  app.kubernetes.io/name: onepassword-connect-operator
  app.kubernetes.io/component: operator
subjects:
  - kind: ServiceAccount
    name: onepassword-connect-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
