apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: amq-cluster-ssl

resources:
  - namespace.yaml
  - operator-group.yaml
  - ../../operator/overlays/v7.12
  - ../../instance/overlays/clustered-ephemeral-tls-letsencrypt

components:
  - ../../instance/components/addresses
  - ../../instance/components/authentication/guest
  - ../../instance/components/logging/claim-template
  - ../../instance/components/metrics/address-metrics
  - ../../instance/components/metrics/broker-internal/jvm
  - ../../instance/components/metrics/broker-external/prometheus

patches:
  - target:
      group: broker.amq.io
      version: v1beta1
      kind: ActiveMQArtemis
      name: default
    patch: |-
      - op: replace
        path: /metadata/name
        value: amq-cluster-ssl

      - op: replace
        path: /spec/console/expose
        value: true

      - op: add
        path: /spec/adminUser
        value: admin
      - op: add
        path: /spec/adminPassword
        value: example
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: console-ssl-certificate
    patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - amq-cluster-ssl-wconsj-0-svc-rte-amq-cluster-ssl.apps.cluster.example.com
          - amq-cluster-ssl-wconsj-1-svc-rte-amq-cluster-ssl.apps.cluster.example.com
          - amq-cluster-ssl-wconsj-2-svc-rte-amq-cluster-ssl.apps.cluster.example.com
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: acceptor-ssl-certificate
    patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - amq-cluster-ssl-ssl-0-svc-rte-amq-cluster-ssl.apps.cluster.example.com
          - amq-cluster-ssl-ssl-1-svc-rte-amq-cluster-ssl.apps.cluster.example.com
          - amq-cluster-ssl-ssl-2-svc-rte-amq-cluster-ssl.apps.cluster.example.com
  - target:
      group: monitoring.coreos.com
      version: v1
      kind: ServiceMonitor
      name: default
    patch: |-
      - op: replace
        path: /metadata/name
        value: amq-cluster-ssl-prometheus-sm
      - op: replace
        path: /spec/selector/matchLabels/application
        value: amq-cluster-ssl-app
