apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apicurio-registry-cert
  annotations:
    acme.cert-manager.io/http01-override-ingress-name: apicurio-registry
    cert-manager.io/issue-temporary-certificate: 'true'
spec:
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: apicurio-registry-cert
  dnsNames:
    # These should be replaced in a kustomize overlay, according to intended hostnames
    - apicurio-registry.apps.cluster.example.com
  usages:
    - digital signature
    - key encipherment
  secretTemplate:
    annotations:
      kubernetes.io/description: >-
        Secret issued via cert-manager which will be referenced and used by Apicurio Registry for securing
        HTTPS traffic
