apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../postgresql
  - apicurio-registry-cert.yaml

components:
  - ../../components/https-ingress

replacements:
  - source:
      group: registry.apicur.io
      version: v1
      kind: ApicurioRegistry
      name: default
      fieldPath: spec.deployment.host
    targets:
      - select:
          group: cert-manager.io
          version: v1
          kind: Certificate
          name: apicurio-registry-cert
        fieldPaths:
          - spec.dnsNames.0
      - select:
          group: networking.k8s.io
          version: v1
          kind: Ingress
          name: apicurio-registry
        fieldPaths:
          - spec.tls.0.hosts.0
          - spec.rules.0.host
