apiVersion: v1
kind: Secret
metadata:
  name: grafana-auth-secret
  annotations:
    kubernetes.io/service-account.name: grafana-sa
    argocd.argoproj.io/sync-wave: "2"
type: kubernetes.io/service-account-token
