---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: sriov-network-operator-subscription
    patch: |-
      - op: replace
        path: /spec/channel
        value: '4.11'
