apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../clustered-ephemeral
  - keystore-inputs.yaml

components:
  - ../../components/acceptors/one-way-tls
  - ../../components/certificates/init-build-keystore/init-container
  - ../../components/certificates/init-build-keystore/console-ssl-keystore
  - ../../components/certificates/init-build-keystore/acceptor-ssl-keystore-and-truststore

replacements:
  - source:
      group: ''
      version: v1
      kind: Secret
      name: keystore-inputs
      fieldPath: stringData.keyStorePassword
    targets:
      - select:
          group: ''
          version: v1
          kind: Secret
          name: console-ssl-keystore
        fieldPaths:
          - stringData.keyStorePassword
      - select:
          group: ''
          version: v1
          kind: Secret
          name: acceptor-ssl-keystore
        fieldPaths:
          - stringData.keyStorePassword
  - source:
      group: ''
      version: v1
      kind: Secret
      name: keystore-inputs
      fieldPath: stringData.trustStorePassword
    targets:
      - select:
          group: ''
          version: v1
          kind: Secret
          name: console-ssl-keystore
        fieldPaths:
          - stringData.trustStorePassword
      - select:
          group: ''
          version: v1
          kind: Secret
          name: acceptor-ssl-truststore
        fieldPaths:
          - stringData.trustStorePassword
