apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: console-ssl-certificate
spec:
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: namespaced-issuer
  secretName: console-ssl-certificate
  dnsNames:
    # These should be replaced in a kustomize overlay, according to intended hostnames

    # Route hostname
    - default-wconsj-0-svc-rte-target-namespace.apps.cluster.example.com
  usages:
    - digital signature
    - key encipherment
  secretTemplate:
    annotations:
      kubernetes.io/description: >-
        Secret issued via cert-manager which will be referenced by an ActiveMQArtemis CR for securing the AMQ web
        console
  keystores:
    jks:
      create: true
      passwordSecretRef:
        name: console-ssl-keystore
        key: keyStorePassword
